server:
  port: 9112
spring:
  application:
    name: consumer-cloud
eureka:
  instance:
    prefer-ip-address: true # 注册服务的时候使用服务的ip地址
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka/