server:
  port: 9100
spring:
  application:
    name: acl-server
  datasource:
    url: jdbc:p6spy:mysql://192.168.1.177:3306/security?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  redis:
    host: 192.168.1.177
    password: root
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-wait: -1
        max-active: 20
        max-idle: 5
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #自动转换大小写
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #输出sql语句
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto # 全局主键策略
      logic-delete-value: 1
      logic-not-delete-value: 0