spring:
  rabbitmq:
    host: dc3-rabbitmq
    port: 5672
    username: root
    password: root
    virtual-host: iot

    publisher-returns: true #消息可靠投递
    template:
      mandatory: true
    #发布确认属性配置   NONE禁用
    #                 CORRELATED发布消息成功到交换器后会触发回调方法
    #                 SIMPLE   两种效果，其一效果和CORRELATED值一样会触发回调方法，
    #                                   其二在发布消息成功后使用rabbitTemplate调用waitForConfirms或waitForConfirmsOrDie方法等待broker节点返回发送结果，
    #                                   根据返回结果来判定下一步的逻辑，要注意的点是waitForConfirmsOrDie方法如果返回false则会关闭channel，
    #                                   则接下来无法发送消息到broker;
    publisher-confirm-type: correlated
    # 接收消息确认
    listener:
      simple:
        acknowledge-mode: manual  #手动消息确认


server:
  port: 9100