server:
  port: 9100

spring:
  datasource:
    url: jdbc:p6spy:mysql://192.168.1.177:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#  security:
#    user:
#      name: root
#      password: root

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #自动转换大小写
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #输出sql语句
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto # 全局主键策略
      logic-delete-value: 1
      logic-not-delete-value: 0