server:
  port: 9101
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: acl-server
          url: lb://acl-server
          predicates:
            - Path: /*/acl/**
