server:
  port: 9106
dubbo:
  application:
    name: producer-test #服务名
  registry:
    address: zookeeper://192.168.1.177:2181
  scan:
    base-packages: com.gitee.dubbo.producer.service #扫描service接口包