spring:
  redis:
    host: 192.168.1.177 #服务器地址
    password: root # 密码
    port: 6379 #端口
    database: 0 #数据库索引默认为0
    lettuce:
      pool:
        max-idle: 10
        min-idle: 10
        max-active: 100